import React, { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Breadcrumbs } from "@/components/checkout/Breadcrumbs";
import { CartProvider } from "@/context/Cart";
import { SuspendedCartDetails } from "@/components/checkout/CartDetails";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CliffRise",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="flex text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white">
        <CartProvider>
          <div className="flex-1 h-full flex flex-col justify-between">
            <Breadcrumbs />
            {children}
            <footer className="h-[100px]">All rights reserved</footer>
          </div>
          <SuspendedCartDetails isFixed={false} />
        </CartProvider>
      </body>
    </html>
  );
};

export default RootLayout;
