import React, { PropsWithChildren } from "react";
import type { Metadata } from "next";
import "../globals.css";
import { Breadcrumbs } from "@/components/checkout/Breadcrumbs";
import { CartProvider } from "@/context/Cart";
import { SuspendedCartDetails } from "@/components/checkout/CartDetails";

export const metadata: Metadata = {
  title: "CliffRise",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className="flex text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white">
        <CartProvider>
          <div className="flex-1 h-full flex flex-col justify-between">
            <Breadcrumbs />
            {children}
            <footer className="h-[100px]">All rights reserved</footer>
          </div>
          <SuspendedCartDetails isFixed={false} />
        </CartProvider>
      </body>
    </html>
  );
};

export default RootLayout;
