import React, { PropsWithChildren } from "react";
import type { Metadata } from "next";
import "../globals.css";
import { Navbar } from "@/components/Navbar";
import { CartProvider } from "@/context/Cart";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "CliffRise",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className="bg-neutral-50 text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white">
        <CartProvider>
          <Navbar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
};

export default RootLayout;
