import classNames from "classnames";
import React, { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { CartProvider } from "@/context/Cart";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CliffRise",
  description: "Generated by create next app",
};

const cn = classNames({
  "bg-neutral-50": true,
  "text-black": true,
  "selection:bg-teal-300": true,
  "dark:bg-neutral-900": true,
  "dark:text-white": true,
  "dark:selection:bg-pink-500": true,
  "dark:selection:text-white": true,
});

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className={cn}>
        <CartProvider>
          <Navbar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
